### PR TITLE
Upgrade to latest swagger-ui & avoid hacks in dist/

### PR DESCRIPTION
**Pull request by gwicke**
- Update to latest swagger-ui and swagger-client.
- Improve x-textarea implementation.
- Get rid of hacks in dist/, and instead use regular patches per-feature in src/ and lib/ & `npm run build`. This will make it easier to re-apply our changes, and possibly also push our changes upstream.

### CODE REVIEW

**Comment by gwicke** [comment]
/cc @wikimedia/services 

This is based on top of the last upstream release, so we'll need to force-push to our master to get rid of previous changes in dist/.

**Comment by Pchelolo** [comment]
Hehe.. It's impossible to review, so just one comment: perhaps we need to update https://github.com/wikimedia/swagger-js too?

**Comment by gwicke** [comment]
@Pchelolo: I already did. We previously pulled in the latest upstream master for that, and I switched it to use our own swagger-js instead.

**Comment by gwicke** [comment]
One issue I found with latest swagger-ui is that scrolling to a particular entry point seems to be broken. The section is still opened, but the user needs to manually scroll to see it.

**Comment by Pchelolo** [comment]
@gwicke hm, the official swagger example doesn't seem to be broken: http://petstore.swagger.io/#!/user/updateUser 

However we don't really know which version there running.

**Comment by d00rman** [comment]
> One issue I found with latest swagger-ui is that scrolling to a particular entry point seems to be broken. The section is still opened, but the user needs to manually scroll to see it.

I noticed this problem even before this PR, so it's not strictly a regression. I'll try to merge this from the command line.

**Comment by gwicke** [comment]
@d00rman, yeah you are right, no scrolling in prod either.

**Pull request merged**
